[package]
name = "use-async-scoped"
version = "0.1.0"
authors = ["michael-grunder <michael.grunder@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-scoped = "0.3.1"
async-std = "1.4.0"
